# Generated by Django 2.2.2 on 2019-06-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='workers',
        ),
        migrations.AddField(
            model_name='workorder',
            name='workers',
            field=models.ManyToManyField(to='workers.Worker'),
        ),
    ]
